create table calculo_periodo (
    id bigint generated by default as identity primary key,
    calculo_id bigint not null references calculo(id) on delete cascade,
    ordem int not null,
    data_inicial date not null,
    data_final date not null,
    indice_utilizado varchar(20) not null
);

create index idx_calculo_periodo_calculo on calculo_periodo (calculo_id);