spring:
  application:
    name: sistema-calculos-judiciais
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/calculos_judiciais
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

app:
  indices:
    import-selic-startup: false