create table indice_economico (
    id bigint generated by default as identity primary key,
    tipo_indice varchar(20) not null,
    competencia date not null,
    valor_percentual numeric(19,8) not null,
    data_importacao date not null,
    fonte varchar(120) not null,
    constraint uk_indice_tipo_competencia unique (tipo_indice, competencia)
);

create index idx_indice_tipo_competencia on indice_economico (tipo_indice, competencia);

create table calculo (
    id bigint generated by default as identity primary key,
    tipo_calculo varchar(30) not null,
    indice_utilizado varchar(20) not null,
    valor_original numeric(19,8) not null,
    valor_final numeric(19,8) not null,
    data_inicial date not null,
    data_final date not null,
    data_criacao timestamp not null
);

create index idx_calculo_data_criacao on calculo (data_criacao desc);

create table calculo_memoria (
    id bigint generated by default as identity primary key,
    calculo_id bigint not null references calculo(id) on delete cascade,
    competencia varchar(7) not null,
    indice_percentual numeric(19,8) not null,
    valor_anterior numeric(19,8) not null,
    valor_corrigido numeric(19,8) not null
);

create index idx_calculo_memoria_calculo on calculo_memoria (calculo_id);